all: clear driver1 driver2

clear:
	@clear

driver1:
	@g++ driver1.cpp tetromino.cpp tetris_board.cpp -o main1.out
	@./main1.out

driver2:
	@g++ driver2.cpp tetromino.cpp tetris_board.cpp -o main2.out
	@./main2.out
