all: compile run clean

compile:
	@echo "COMPILING TEST DRIVER...\n"
	@javac TestClass.java
	
run:
	@echo "-------------------------------------------"
	@java TestClass

clean:
	@rm -f *.class
	
